.circleci/config.yml, common/config.js, common/data/oauth.js, helm_deploy/values-development.yaml
Tweaks OAuth endpoint config to include the path as well as the host.
=> Make oauth endpoint slightly more configurable

.eslintignore, app/questiongroup/index.njk, app/questions/get.controller.js, app/questions/index.njk, app/router.js, common/data/assessmentApi.js, wiremock/assessmentApi.js, wiremock/responses/questionList.json, wiremock/stub.js
Add new page, listing top level forms we can fill in
=> Question list

app/questiongroup/index.njk, app/questiongroup/post.controller.js, app/router.js, common/data/assessmentApi.js
Gathers up the answers, shuffles them into the shape the backend wants, fires them off.
=> Save answers

common/middleware/getOffenderDetails.js, common/middleware/getOffenderDetails.test.js
- Grab assessmentId from params
- Fixed subject path
=> Offender details fixes 

app/psrFromCourt/post.controller.js, app/questionGroup/post.controller.js, app/questionGroup/post.controller.test.js, common/data/assessmentApi.js, wiremock/assessmentApi.js
* Always update the current episode
* Actually corrected the subject path
* Fixed Cypress tests
=> Update current episode

app/questionGroup/post.controller.js, app/questionGroup/post.controller.test.js, app/router.js
Date fields now work properly with mandatory field validation rules.
=> Reconstruct dates before applying validation rules.

app/questionGroup/fixtures/expected.json, app/questionGroup/get.controller.js, common/assets/sass/application.scss, common/templates/components/question/template.njk, package-lock.json, package.json, wiremock/responses/assessmentEpisodes.json, wiremock/responses/questionGroups.json
- Displays questions marked 'readonly' as a summary table
- Correctly preselects answers for radio and checkbox questions when previous answers from the assessment episode are present
- correctly selects multiple checkbox answers after a submit fails validation and redisplays the page
=> Arn 251 offender information page

package-lock.json, package.json
NPM Audit raised a warning regarding vulnerabilities when installing packages this morning
Resolve the following
- https://www.npmjs.com/advisories/1650
- https://www.npmjs.com/advisories/1654
=> Fix vulnerabilities raised from NPM audit

app/assessmentFromCrn/get.controller.js, app/assessmentFromCrn/index.njk, app/assessmentFromCrn/post.controller.js, app/router.js, common/data/hmppsAssessmentApi.js, wiremock/assessmentApi.js, wiremock/stub.js
Add create assessment from CRN helper page
=> Update create assessment endpoint

common/assets/javascripts/filtered-reference-data.js, common/middleware/getQuestionGroup.js, common/middleware/getQuestionGroup.test.js, wiremock/responses/questionGroups.json
Context
This PR aims to fix the below issues with filtered reference data
Intent
Add support for multiple reference fields
Add support for optional reference fields
Add dynamic-* input types - to support questions without targets
=> Update integration for filtered ref data

.eslintignore, app/questionGroup/fixtures/expected.json, app/questionGroup/get.controller.js, app/questionGroup/post.controller.js, common/assets/sass/_pages.scss, common/templates/components/question/template.njk, wiremock/responses/assessmentEpisodes.json, wiremock/responses/questionGroups.json
PR displays a 'table' type question group, along with answers supplied as an array, as outlined in https://github.com/ministryofjustice/hmpps-assessments-api/pull/138
=> Arn 347 display children at risk

README.md, app/summary/index.njk, app/summary/post.controller.js, app/summary/post.controller.test.js, app/summary/success.njk, common/config.js, common/data/hmppsAssessmentApi.js, common/templates/partials/offenderDetails.njk, docker-compose.yml, integration-tests/integration/assessments/completeAssessment.spec.js, integration-tests/pages/assessments/assessmentPreSentenceSummaryPage.js, integration-tests/plugins/index.js, wiremock/assessmentApi.js, wiremock/assessmentFromDelius.js, wiremock/start.js, wiremock/stub.js
Created new separate page for the successful completion of an assessment.
When we click Complete Assessment button a new page is displayed with the submission confirmation.
=> Arn 352 complete assessment success

app/addRow/fixtures/expected.json, app/addRow/get.controller.js, app/addRow/get.controller.test.js, app/addRow/index.njk, app/addRow/post.controller.js, app/addRow/post.controller.test.js, app/questionGroup/fixtures/expected.json, app/questionGroup/get.controller.js, app/questionGroup/post.controller.js, app/questionGroup/post.controller.test.js, app/router.js, common/assets/sass/_pages.scss, common/data/hmppsAssessmentApi.js, common/question-groups/get-question-groups.js, common/question-groups/post-question-groups.js, common/templates/components/question/macro.njk, common/templates/components/question/template.njk, common/utils/util.js, server.js, wiremock/responses/questionGroups.json
Adds ui functionality to add a new row to a table. Renders a page with the table questions and UI elements when at an endpoint of the form `<baseurl>/<episode_id>/questiongroup/<questiongroup_id>/<section>/<page>/addrow/<table_name>`.
On submit, redirects to the parent section and page.
=> Arn 356 add child

common/data/oauth.js, common/middleware/auth.js, common/utils/constants.js, server.js
- Create constants to increase readability of token lifetimes
- Adjust session lifetime to be less than refresh token lifetime
=> Update cookie and session lifetime

app/deleteRow/get.controller.js, app/deleteRow/index.njk, app/deleteRow/post.controller.js, app/router.js, common/data/hmppsAssessmentApi.js, common/templates/components/question/template.njk, package-lock.json, wiremock/assessmentApi.js, wiremock/stub.js
Displays a UI page to allow the user to confirm the deletion. Any action except selecting 'yes' to the confirmation returns to the parent page displaying the table.
=> ARN-358 allows the user to delete a row from a table object

common/question-groups/post-question-groups.test.js
Adds missing coverage for the functions in `post-questions-groups.js`, hopefully this helps documents some of the behaviour around conditional validation
=> Add coverage for post question group

.eslintignore, app/router.js, app/summary/fixtures/expected.json, app/summary/get.controller.js, app/summary/get.controller.test.js, common/data/hmppsAssessmentApi.js, common/middleware/getQuestionGroup.js, common/middleware/getQuestionGroup.test.js, integration-tests/plugins/index.js, package-lock.json, package.json, wiremock/assessmentApi.js, wiremock/responses/questionGroupSummary.json, wiremock/responses/questionGroups.json, wiremock/stub.js
This PR updates the UI to get assessment summaries and questions based on the assessment type, via 2 new API endpoints:
GET /assessments/schema/ROSH
GET /assessments/schema/ROSH/summary
=> Arn 516 use new assessment endpoints

app/questionGroup/fixtures/expected.json, common/question-groups/get-question-groups.js, common/templates/components/question/template.njk, wiremock/responses/questionGroups.json
In response to the update in `hmpps-assessments-api`
=> Rename TableQuestionDto to tableGroup

common/assets/sass/components/_predictor-scores.scss
Fix colours on the predictor scores page to be inline with the designs in Figma
=> Fix predictor colours

common/middleware/form-wizard-validators/validators.js, common/middleware/form-wizard-validators/validators.test.js
Fixes a bug caused by not converting form inputs from strings to numbers.
=> ARN-609 validation bug fix

app/rsr/controllers/saveAndContinue.test.js
Add additional assertions to test for generated `input` HTML elements in  pre-rendered conditional questions
=> Add additional assertions to conditional question tests

app/startAssessment/get.controller.js, app/startAssessment/get.controller.test.js
When the ARN service is started from a URL in the form 
```https://dev.hmpps-assessments.service.justice.gov.uk/assessment-from-delius?crn=X466472&eventId=2500548601&assessmentType=UNPAID_WORK```
ARN will add a parameter `deliusEventType: "EVENT_ID"` to the Assessment DTO when creating an assessment.
=> ARN-782 include 'deliusEventType' when creating assessment from Delius link

app/common/controllers/saveAndContinue.js, app/upw/fields.js
This PR addresses 2 defects:
1) Now throws validation errors when details text boxes contain only spaces
2) Disposes of raw validation errors once they are formatted for display, so that they don't display on any subsequent pages
=> Arn 654 upw risk section pages

app/upw/controllers/taskList.js, app/upw/steps.js, app/upw/templates/assessment-saved.njk, app/upw/templates/taskList.njk, common/assets/sass/_upw-pages.scss
- Update the Confirmation page
- Create Assessment Saved page
- Remove Save and Close buttons
=> Amend save and close

app/upw/controllers/declaration.js, app/upw/steps.js, app/upw/templates/declaration.njk, app/upw/templates/diversity-information/cultural-and-religious-adjustments.njk, app/upw/templates/diversity-information/gender-information.njk, app/upw/templates/diversity-information/placement-preferences.njk, app/upw/templates/employment-education-skills/employment-education-skills.njk, app/upw/templates/employment-education-skills/training-employment-opportunities.njk, app/upw/templates/individuals-details/edit-contact-details.njk, app/upw/templates/individuals-details/edit-emergency-contact-details.njk, app/upw/templates/individuals-details/edit-personal-details.njk, app/upw/templates/individuals-details/individuals-details.njk, app/upw/templates/placement-details/availability.njk, app/upw/templates/placement-details/equipment.njk, app/upw/templates/placement-details/intensive-working.njk, app/upw/templates/placement-restrictions/caring-commitments.njk, app/upw/templates/placement-restrictions/disabilities-and-mental-health.njk, app/upw/templates/placement-restrictions/edit-gp-details.njk, app/upw/templates/placement-restrictions/gp-details.njk, app/upw/templates/placement-restrictions/health-issues.njk, app/upw/templates/placement-restrictions/travel-information.njk, app/upw/templates/risk-information/managing-risk.njk, app/upw/templates/risk-information/risk-of-harm-in-the-community.njk, app/upw/templates/start.njk, common/templates/components/widgets/template.njk
- Add missing widgets to declaration sections
- Add missing heading to widgets section
- Fix layout of pages with widget section
=> Fix widget defects

app/error.njk, app/upw/controllers/confirmation.js, app/upw/controllers/confirmation.test.js, app/upw/templates/pdf-preview-and-declaration/components/pdf-template/template.njk, server.js
PDF Changes:
- Adds GP Name
- Alters declaration text
- if Mappa nominal, show widget and hide nominal question. If Mappa nominal is false, do not display widget and display nominal question.
Updates error page to display at correct width
Alters PDF upload error to show nDelius upload instructions for a wider range of upload errors.
Removes upw_ from some field names
=> Arn 550 pdf layout

common/utils/util.js, common/utils/util.test.js
Fixes a bug with formatting minutes when rendering date and time
=> Add test coverage for date utils

app/common/controllers/saveAndContinue.js, app/common/controllers/saveAndContinue.test.js
Calling the super `configure` method early was creating a race condition, this caused questions to be missing on the page intermittently
=> Update save and continue controller to remove race condition

app/upw/templates/pdf-preview-and-declaration/components/pdf-template/macro.njk, app/upw/templates/pdf-preview-and-declaration/components/pdf-template/template.njk, app/upw/templates/pdf-preview-and-declaration/pdf-preview.njk
Related to the `404` responses we saw in the performance testing
=> Fix 404 on PDF preview page

app/rsr/steps.js, app/upw/steps.js, app/upw/templates/cookies.njk, common/templates/layout.njk
Cookie link now included in the footer of the page, once clicked it redirects the user to the cookie policy.
=> Arn 751 cookie policy link

.trivyignore, Dockerfile, helm_deploy/hmpps-risk-assessment-ui/templates/ingress.yaml
Remove typo from Dockerfile user
=> Arn 897 revert node version

app/upw/controllers/editContactDetailsSaveAndContinue.js, app/upw/controllers/individualsDetailsSaveAndContinue.js, app/upw/fields.js, app/upw/steps.js
county and district fields changed to be made non-mandatory
=> Arn 870 mandatory contact fields

app/upw/controllers/confirmation.js, app/upw/controllers/confirmation.test.js, common/data/hmppsAssessmentApi.js, wiremock/assessmentApi.js
This PR adds a new assessment completion endpoint which is idempotent, and hooks up the UPW assessment to use it.
=> ARN-987 new assessment completion endpoint

README.md
This PR is to force a rebuild of our Docker image in order to pull the latest Debian packages
=> Force rebuild of main

.circleci/config.yml, app/common/controllers/saveAndContinue.js
Fixes for bugs found during integration
Removes redundant Cypress tests from the CI pipeline
=> Arn 859 multiple data entries integration

app/common/controllers/saveAndContinue.js, app/upw/templates/individuals-details/individuals-details.njk, app/upw/templates/placement-restrictions/gp-details.njk
* Refactor function parameters to use destructuring for readability
* Update templates to use multiples data from group arrays
=> Tidy up multiples code

app/upw/templates/individuals-details/individuals-details.njk
Looks like we were passing arrays rather than strings to the the `read-only` components, this PR should fix that issue
=> Update contact details to use rawAnswers

app/common/controllers/saveAndContinue.js, app/common/controllers/saveAndContinue.test.js
Removed some code that is causing issues when editing GP/EC details. I don't believe this code is used, I've updated the templates to use the structured data in a previous PR
=> Remove code that is causing fields to be merged for multiples data

common/logging/app-insights.js
Updates assessment UUID and episode UUID names sent to Application Insights to match the parameters sent by the API
=> Updates AppInsights parameters

app/upw/templates/pdf-preview-and-declaration/components/pdf-template/template.njk
Adds some missing questions from the disabilities section of the UPW PDF
=> Add missing disabilities questions to the UPW PDF

app/upw/templates/pdf-preview-and-declaration/components/pdf-template/template.njk, app/upw/templates/placement-restrictions/caring-commitments.njk, wiremock/responses/assessmentEpisodes.json
**Carer commitments page**
**PDF Template**
=> Update templates for carer-commitments

app/upw/templates/pdf-preview-and-declaration/components/pdf-template/template.njk
- Add IDs to section headings
- Fix duplicate IDs on certain rows
- Refactor heading levels to give structue when using a screenreader
=> Update UPW PDF template

app/common/controllers/saveAndContinue.js, app/common/controllers/saveAndContinue.test.js, app/upw/controllers/carerCommitment.js, app/upw/controllers/closeAssessment.test.js, app/upw/controllers/confirmation.js, app/upw/controllers/confirmation.test.js, app/upw/controllers/convertPdf.js, app/upw/controllers/gpDetailsSaveAndContinue.js, app/upw/controllers/individualsDetailsSaveAndContinue.js, app/upw/controllers/removeMultipleGroupItem.js, app/upw/controllers/removeMultipleGroupItem.test.js, app/upw/controllers/saveAndContinue.js, app/upw/controllers/taskList.js, app/upw/controllers/taskList.test.js, app/upw/templates/individuals-details/individuals-details.njk, app/upw/templates/pdf-preview-and-declaration/components/pdf-template/macro.njk, app/upw/templates/pdf-preview-and-declaration/components/pdf-template/template.njk, app/upw/templates/pdf-preview-and-declaration/pdf-preview.njk, app/upw/templates/pdf-preview-and-declaration/pdf.njk, app/upw/templates/placement-restrictions/caring-commitments.njk, app/upw/templates/placement-restrictions/components/disabilities/macro.njk, app/upw/templates/placement-restrictions/components/disabilities/template.njk, app/upw/templates/placement-restrictions/disabilities-and-mental-health.njk, app/upw/templates/placement-restrictions/gp-details.njk
Rename the cached object `rawAnswers` to reflect what it actually is, a cached version of the answers persisted in the backend
=> Rename rawAnswers cache object

app/common/controllers/saveAndContinue.js, app/common/controllers/saveAndContinue.test.js, app/upw/controllers/carerCommitment.js, app/upw/controllers/gpDetailsSaveAndContinue.js, app/upw/controllers/individualsDetailsSaveAndContinue.js, app/upw/controllers/removeMultipleGroupItem.js, app/upw/controllers/removeMultipleGroupItem.test.js, app/upw/controllers/saveAndContinue.js, app/upw/controllers/taskList.js, app/upw/controllers/taskList.test.js, common/data/localCache.js, common/data/oauth.js, common/utils/constants.js
Bit of a tidy up, should make PR's smaller in the event we have to update these again in the future
=> Refactor caching keys to be constants

app/upw/controllers/common.utils.js, app/upw/controllers/common.utils.test.js, common/templates/components/rosh-widget/template.njk, wiremock/responses/roshRiskSummary.json
Update integration in response to https://github.com/ministryofjustice/hmpps-assessments-api/pull/552
=> Update RoSH widget integration with updated endpoint

app/upw/controllers/confirmation.js
This PR updates the confirmation controller to
- upload PDF and complete the assessment in parallel
- safely handle failures to ensure the assessment is completed even if the PDF fails to upload
It should hopefully also mean that this controller executes slightly faster now
=> Refactor confirmation controller

app/upw/controllers/api.js, app/upw/controllers/api.test.js, common/data/aws.js
- Improve error handling in API middleware
=> Add default for statusCode in the UPW API endpoint

app/upw/controllers/api.js, common/data/aws.js
=> Fix typo in S3 fetch method

app/common/controllers/saveAndContinue.js, app/common/controllers/saveAndContinue.test.js, app/startAssessment/get.controller.js, app/startAssessment/get.controller.test.js, app/upw/controllers/api.js, app/upw/controllers/api.test.js, app/upw/controllers/confirmation.js, app/upw/controllers/confirmation.test.js, app/upw/controllers/removeMultipleGroupItem.js, app/upw/controllers/removeMultipleGroupItem.test.js, app/upw/controllers/start.js, app/upw/controllers/start.test.js, app/upw/controllers/taskList.js, app/upw/fields.js, common/data/hmppsAssessmentApi.js, common/data/hmppsAssessmentApi.test.js, common/data/pdf.js, common/middleware/getOffenderDetails.js, common/middleware/getOffenderDetails.test.js, wiremock/assessmentApi.js
Will follow up with a PR in the assessments API to add the endpoint `/episode/{episodeUUID}`, the episode ID should be unique enough that we won't have any issues creating it
=> ARN 1371 - regenerate UPW PDF when not found in S3

app/upw/controllers/api.js, app/upw/controllers/common.utils.js, app/upw/controllers/common.utils.test.js, app/upw/controllers/saveAndContinue.js, app/upw/controllers/taskList.js, common/data/hmppsAssessmentApi.js
- Update call to registrations endpoint to include the event ID
- Update calls to registrations method to pass through the event ID
- Fix tests etc..
=> Refactor registrations integration

common/data/hmppsAssessmentApi.js
=> Fix typo when calling the registrations endpoint

helm_deploy/hmpps-risk-assessment-ui/values.yaml
- Update notification banner content
- Update maintenance page content
=> Enable to the notification banner

helm_deploy/hmpps-risk-assessment-ui/values.yaml
- disable the notification banner
=> Enable maintenance page

app/upw/templates/pdf-preview-and-declaration/components/pdf-template/template.njk, app/upw/templates/placement-restrictions/components/render-disabilities/macro.njk, app/upw/templates/placement-restrictions/components/render-disabilities/template.njk, app/upw/templates/placement-restrictions/components/render-provisions/macro.njk, app/upw/templates/placement-restrictions/components/render-provisions/template.njk, app/upw/templates/placement-restrictions/disabilities-and-mental-health.njk, common/utils/util.js, common/utils/util.test.js, server.js, wiremock/responses/assessmentEpisodes.json
=> Arn 1583 disabilities and provisions

.circleci/config.yml
This is not required and will default to config from  environment variables
=> ARN-2041 - Remove dev context from Circle config
