ministryofjustice/hmpps-risk-assessment-ui

app/questiongroup/get.controller.js
app/questiongroup/index.njk
app/questiongroup/post.controller.js
app/questions/get.controller.js
app/router.js

As the title. I've done this pretty quickly and feels a bit filthy, so if want to do it a different way or want to rip it out once the Show and Tell's done, that's fine
Once https://github.com/ministryofjustice/hmpps-assessments-api/pull/30 is merged down, the 'Layer 3' assessment will have two subgroups, and will show off this change.

Navigate through the form's subgroups, in turn.

---

app/questiongroup/get.controller.js
app/questiongroup/index.njk

Rather than passing the questions and the answer into the template separates, use the answers to annotate the question structure directly, adding an answer field and adding a checked field into the answerSchemas.
This simplifies the template slightly for text fields, and lets radio buttons roundtrip without any jiggery-pokery in the template.

Round-trip radio buttons

---

app/questionGroup/get.controller.js

This [API PR](https://github.com/ministryofjustice/hmpps-assessments-api/pull/94) adds a readonly to the questions. When true, those fields should be display only in the UI. 
This PR makes that change. For questions marked read only is builds readonly and disabled attributes, which get passed down to the govuk input widgets. I've mark disabled in addition to readonly because it's a very clear visual cue that it's working. What we actually want is some proper styling, but that's some distance beyond my comfort zone.

Enable read only fields

---

app/psrFromCourt/post.controller.js
app/questionGroup/post.controller.js
app/questionGroup/post.controller.test.js
common/data/assessmentApi.js

Tweak `postData` to return a ok/fail flag as well as the response body, so we can handle client-side recoverable failures separately from unrecoverable exceptions.
Pick this flag up in `saveQuestionGroup` and redisplay existing page with error annotations if the save wasn't successful.

Arn 340 surface errors from backend

---

common/middleware/getQuestionGroup.js
common/middleware/getQuestionGroup.test.js
common/templates/components/question/template.njk
wiremock/responses/assessmentEpisodes.json

Currently answers are not being displayed for reference data fields, I believe this is down to myself misunderstanding the role of `answerSchema` on a `questionSchema`
- Select a "Source of Information"
- Save
- Reload the page
**expected:** the selected options are presented back to the user
**actual:** the selected options are not presented back to the user
- Remove use of options field in favour of `answerSchema`
- Revert template to solely use `answerSchema`
- Update WireMock stubs to have answers for Sources of Information
- Update check for whether a `questionSchema` is part of a group to be consistent with the rest of the codebase

Fix issue with answers not being displayed for reference data

---

app/questionGroup/get.controller.js
common/assets/sass/application.scss
common/templates/components/question/template.njk

Layout and rendering tweaks. They'll apply generally, but prompted by the ROSH Previous convictions section. 
* 'noinput' input type. For rendering questions which have business rules attached, but don't have any input of they're own - "Has the individual been convicted of any of the following offences ...", for example. 
See related assessment-api PR https://github.com/ministryofjustice/hmpps-assessments-api/pull/136

Arn 370 ROSH Previous Convictions Questions

---

app/questionGroup/get.controller.js
app/questionGroup/get.controller.test.js
app/questionGroup/index.njk
app/referenceData/post.controller.js
app/referenceData/post.controller.test.js
app/router.js
common/assets/javascripts/filtered-reference-data.js
common/data/hmppsAssessmentApi.js
common/middleware/getQuestionGroup.js
common/middleware/getQuestionGroup.test.js
integration-tests/integration/questions/filtered-reference-data.spec.js
integration-tests/pages/questions/filteredReferenceDataTestPage.js
integration-tests/pages/questions/questionsPage1.js
integration-tests/plugins/index.js
wiremock/referenceData.js
wiremock/responses/filteredReferenceData.json
wiremock/responses/questionGroupSummary.json
wiremock/responses/questionGroups.json

This PR is to update the frontend to support filtered reference data
- Add WireMock stubs
- Update the client to pull filtered reference data from the assessment API
- Create an API endpoint for use by the client
- Create client-side javascript to fetch filtered reference data
- (fixed with the [PR](https://github.com/ministryofjustice/hmpps-assessments-api/pull/142)) This code relies on the `parentFields` supplying UUIDs instead of field names

Arn 361 fetch filtered reference data

---

common/assets/javascripts/filtered-reference-data.js
common/middleware/getQuestionGroup.js
common/middleware/getQuestionGroup.test.js
integration-tests/integration/questions/filtered-reference-data.spec.js
wiremock/responses/filteredReferenceData.json
wiremock/responses/questionGroups.json

This PR adds support for radio groups when fetching filtered reference data
- Add support for radios in `filtered-reference-data.js` client-side code
- Update Wiremock to more accurately reflect a scenario for reference data

Add support for radio groups with dynamic ref data

---

common/data/hmppsAssessmentApi.js
common/data/oauth.js
common/data/offenderAssessmentApi.js

Be explicit with what we log, so that we don't log things we shouldn't

Tidy up logging errors when API requests fail

---

common/data/oauth.js
common/data/oauth.test.js
common/data/redis.js
common/middleware/auth.js
common/middleware/auth.test.js
common/middleware/getQuestionGroup.js
common/middleware/getQuestionGroup.test.js
common/models/user.js
server.js

This PR updates the Passport integration to separate out user details and user session, the user details are cached with the key `user:${user.id}` - allowing backend services to retrieve the cached data by information passed in the JWT
- Update passport integration to store user details and session data separately in Redis
- Fix issue where user token was passed in place of API bearer token
- Update OAuth client to cache API bearer token in Redis to support horizontal scaling

ARN 418 get user email

---

app/error.njk
helm_deploy/hmpps-risk-assessment-ui/templates/_envs.tpl
helm_deploy/values-development.yaml
server.js

Not sure if this is something we want, but might help diagnose errors thrown in the application 🤔 
This PR adds the stack trace to error pages, this is behind a feature toggle and enabled for Development.

Add stack-trace to error page with feature toggle

---

app/error.njk
app/router.js
common/data/oauth.js
common/data/oauth.test.js
common/data/offenderAssessmentApi.js
common/middleware/auth.js
common/middleware/auth.test.js
common/templates/partials/header.njk
common/utils/errors.js
package-lock.json
package.json
server.js
wiremock/auth.js

Currently failures when fetching user details fails with a generic error message. This PR aims to update the application to gracefully handle failures when hydrating the user object.
- Improve error handling when hydrating the user object
- Add error handlers for authentication and the other routes
**Unable to fetch user email from HMPPS auth**
**Unable to fetch OASys user - not found for the provided email**
**Unable to fetch OASys user - something else has gone wrong**
**Generic error handling**
**Page not found**
The content for the errors is placeholder - with the focus of this PR to improve our error handling around auth

ARN 418 handle auth failures

---

app/assessmentFromCrn/post.controller.js
app/assessmentFromCrn/post.controller.test.js
app/error.njk
app/questionGroup/post.controller.js
app/questionGroup/post.controller.test.js
app/router.js
app/summary/post.controller.js
app/summary/post.controller.test.js

We require additional details for the following scenarios
- Failure to create an assessment because of insufficient user permissions
- Failure to create an assessment because an offender record already exists
For this PR the handling of these errors is done in the controller to avoid a bigger rework of the assessments client, this is something we can explore at a later date if/when similar is introduced for other parts of the applications
There is also a requirement to show the offender details as part of the error message, this has been intentionally missed as to tackle in a subsequent PR - still need to figure this one out 🤔
Requires [PR 177 of HMPPS Assessments API](https://github.com/ministryofjustice/hmpps-assessments-api/pull/177)

Add initial error handling when creating assessments

---

.circleci/config.yml

Increases size of docker resource being used to run Cypress in CI, as per what some other teams have done (https://github.com/ministryofjustice/prisonstaffhub for example).
Hopefully this will lead to more reliability when running the tests.

Increase resources available for docker image when running Cypress tests

---

app/assessmentFromCrn/post.controller.js
app/assessmentFromCrn/post.controller.test.js
app/psrFromCourt/post.controller.js
app/questionGroup/post.controller.js
app/questionGroup/post.controller.test.js
app/router.js
app/summary/post.controller.js
app/summary/post.controller.test.js
common/data/hmppsAssessmentApi.js

- Move functional error messages to subHeading
- Handle 400/403 errors in HMPPS Assessment API Client
- Remove redundent wrapper around assessment from CRN middleware

Fix handling of 400 and 403 errors

---

common/middleware/area-selection.js

Fixes a bug where regions were not saved in the session when the user had a single area, this is unlikely to happen as the user would never be presented the area selection page as part of the usual flow - but is technically still possible if they were to navigate to the area selection page manually

Fix area selection validation when user has single area

---

common/middleware/auth.js
common/middleware/auth.test.js

We no longer use connect flash - this PR removes passport configuration related to it

Remove flash from passport config

---

app/assessmentFromCrn/index.njk
app/assessmentFromCrn/post.controller.js
app/assessmentFromCrn/post.controller.test.js
app/router.js
app/summary/get.controller.js
app/summary/get.controller.test.js
common/data/hmppsAssessmentApi.js

This PR intends to fix and issue we're seeing in Dev where the `AssessmentFromCRN` fails due to switching over to `assessmentSchemaCode` on the `hmpps-assessments-api`
I have also renamed other usages where I be it to be appropriate
**Expected**
- Navigate to `/assessment-from-delius`
- Fill out the form with a valid CRN and Assessment Schema Code
- Submit
- An assessment is created
**Actual**
- Navigate to `/assessment-from-delius`
- Fill out the form with a valid CRN and Assessment Schema Code
- Submit
- A `400` is returned from the API
**The error**
```
JSON parse error: Instantiation of [simple type, class uk.gov.justice.digital.assessments.api.CreateAssessmentDto] value failed for JSON property assessmentSchemaCode due to missing (therefore NULL) value for creator parameter …
```

Fix AssessmentFromCRN request DTO

---

app/addRow/fixtures/expected.json
app/editRow/fixtures/expected.json
app/questionGroup/fixtures/expected.json
app/questionGroup/get.controller.test.js
common/question-groups/get-question-groups.js

This PR aims to fix a broken integration with the backend API where blank answers are no longer persisted. The tests were already built around null answer types - however these were (AFAIK) never supplied in Dev as the answers would always be persisted as `""` if they were not filled in.
- Update GetQuestionGroups to provide default answers where non is available
- Update Tests and Fixtures
This PR sets a default for answers which is `""` as it would have previously been

Add support for no answers

---

app/predictorScores/get.controller.js
app/predictorScores/get.controller.test.js
app/predictorScores/index.njk
app/questionGroup/post.controller.js
app/questionGroup/post.controller.test.js
app/router.js
app/submitPredictorScores/get.controller.js
app/submitPredictorScores/get.controller.test.js
app/submitPredictorScores/index.njk
common/assets/javascripts/predictors.js
common/assets/sass/application.scss
common/assets/sass/components/_predictor-scores.scss
common/data/predictorScores.js
common/templates/components/predictor-indicator/macro.njk
common/templates/components/predictor-indicator/template.njk
common/templates/components/predictor-score/macro.njk
common/templates/components/predictor-score/template.njk
common/templates/components/predictor-timeline-item/macro.njk
common/templates/components/predictor-timeline-item/template.njk
common/templates/components/predictor-timeline/macro.njk
common/templates/components/predictor-timeline/template.njk
common/utils/constants.js
integration-tests/integration/predictors/predictors.spec.js
integration-tests/pages/predictors/predictorsPage.js
wiremock/assessmentApi.js
wiremock/responses/questionGroupSummary.json
wiremock/responses/questionGroups.json
wiremock/responses/updateEpisode.json

This PR adds the predictor scores page to the RSR assessment, predictors are calculated when submitting the `Needs` section of the `RSR` and cached for the following pages.
- Create predictor scores page template
- Create predictor score components
- Create predictor confirmation page
The mocked responses assume the predictor scores to be returned from the assessments API when updating an episode with the following shape
```json
"episodeId": 1,
"episodeUuid": "22222222-2222-2222-2222-222222222222",
"assessmentUuid": "fb6b7c33-07fc-4c4c-a009-8d60f66952c4",
"reasonForChange": "new episode",
"created": "2019-11-14T08:11:53.177108",
"answers": {},
"predictors": [
{
"type": "RSR",
"scores": [
{ "level": "HIGH", "score": 11.34, "isValid": true, "date": "2020-07-01T12:00:00" },
{ "level": …
```

ARN 522 show RSR predictor scores in the UI

---

app/editRow/get.controller.js
app/editRow/get.controller.test.js
app/questionGroup/get.controller.js
common/data/hmppsAssessmentApi.js
common/middleware/questionGroups/getHandlers.js
wiremock/assessmentApi.js
wiremock/responses/assessmentEpisodes.json
wiremock/stub.js

This PR fixes the integration with the assessments API following the Tables/Answers refactor
- Update endpoints for tables
- Update WireMock stubs
- Update `annotateWithAnswers` usage to use Table entries
Changes in this PR are related to the ones in the PR for the Assessment API
- https://github.com/ministryofjustice/hmpps-assessments-api/pull/280

Fix integration when handling answers and table data

---

app/questionGroup/fixtures/expected.json
common/middleware/questionGroups/getHandlers.js
wiremock/responses/assessmentEpisodes.json
wiremock/responses/questionGroups.json
wiremock/responses/updateEpisode.json

Fixes rendering of entries for a table, previously we were only showing the first table entry. This was caused by the shape of the data changing in a previous refactor.
I've also took an extract of the ROSH question schema and updated the Wiremock stub to better reflect Dev
- There is still an outstanding issue where multiple choice fields fail to render inside a table, this would mean adding the functionality to the existing templates, it may make sense to resolve at a later date when moving ROSH to form-wizard

Fix table entries rendering

---

app/rsr/controllers/saveAndContinue.js
app/rsr/controllers/saveAndContinue.test.js

Fixes an issue with the call to `getAnswers` in the RSR workflow. I've also updated the `postAnswers` call to use the `episodeUuid` as opposed to `current`

Fix call to getAnsers in RSR

---

app/rsr/controllers/saveAndContinue.js
app/rsr/controllers/saveAndContinue.test.js

This PR intends to tidy up the data persisted in the backend, specifically for empty answers
**previously**
```json
{
"some_question": ["some value"],
"some_unanswered_selection": [],
"some_unanswered_question": [""]
}
```
**updated**
```json
{
"some_question": ["some value"],
"some_unanswered_selection": [],
"some_unanswered_question": []
}
```

Tidy up postAnswers DTO

---

app/upw/controllers/confirmation.js
app/upw/controllers/confirmation.test.js
app/upw/steps.js
app/upw/templates/delius-error.njk
common/data/hmppsAssessmentApi.js
common/data/pdf.js
integration-tests/plugins/index.js
wiremock/assessmentApi.js
wiremock/stub.js

This PR creates a controller for the confirmation page with the following behaviour
- Convert HTML template to PDF using Gotenberg
- Upload the PDF document to Delius via the Assessments API
- Handle conversion errors by redirecting to the error page
- Handle 4xx errors by redirecting to the error page
- Handle 5xx "Delius is down" errors by redirecting to the bespoke error page

Create confirmation controller

---

app/upw/controllers/convertPdf.js
app/upw/controllers/saveAndContinue.js
app/upw/controllers/start.js
common/logging/app-insights.js
common/utils/constants.js
package-lock.json
package.json

Adds basic Application Insights event tracking.
Events fired are: 
- **arnNoRoshDataAvailable** - whenever a ROSH check is done and there is no OVERALL_RISK data. A future enhancement might be to cache the ROSH data so the call only happens once per session.
- **arnSessionStarted** - when the Unpaid Work start page is displayed
- **arnPdfDownload** - when the PDF is downloaded
- **arnSectionStarted** - when a section is started. Custom property 'sectionName' is also added the the title of the current page
- **arnSectionCompleted** - when the user completes a page. Custom properties 'sectionName' (title of the current page) and 'completed' (a boolean which is true if the user selected 'yes' to the section complete question). 
Other data included with each event call are:
- assessmentUuid
- …

Arn 806 app insights

---

app/upw/templates/pdf-preview-and-declaration/components/pdf-template/template.njk
common/utils/util.test.js

Fixes and issue with the DoB missing from the PDF. We weren't accessing the `rawAnswers[field]` correctly in the template and the `prettyDate` function was returning `null`. I've also included coverage for ISO Date values when calling `prettyDate` as I noticed this is the format for the DoB field.

Fix bug with missing DoB on the UPW PDF

---

app/upw/controllers/closeAssessment.js
app/upw/controllers/closeAssessment.test.js
app/upw/steps.js
app/upw/templates/close-assessment.njk
common/data/hmppsAssessmentApi.js
integration-tests/plugins/index.js
wiremock/assessmentApi.js
wiremock/stub.js

This PR creates an endpoint `/UPW/close-assessment` that will close the currently selected assessment. It has currently no link in the UI, this however could be added later following the design/content around this.

Add endpoint to close an assessment

---

Dockerfile

Currently blocks the Docker Build task in Circle CI as `node-gyp` after the Node 16 upgrade requires Python 3

Update DockerFile to install Python 3 for use with node-gyp

---

app/upw/templates/pdf-preview-and-declaration/pdf-preview.njk
app/upw/templates/pdf-preview-and-declaration/pdf.njk
common/data/userDetailsCache.js
common/middleware/add-user-information.js
common/middleware/add-user-information.test.js
common/middleware/auth.test.js
common/models/user.js

This PR intends to update the `User` model to store the `name` in the JWT. Looking at the JWT for my user when signed in, it looks like this might allow us to display the user's full name for the PDF template
```
...
{
"sub": "LCAIRNS",
"user_name": "LCAIRNS",
"name": "Lucas Cairns",
...
}
...
```
I've also made sure we fallback to the `user_name` if the `name` attribute is for whatever reason unavailable

Update use to contain full name

---

docker-compose.yml

hmpps-auth now uses this to validate the ITAG_USER user.

Adds `nomis-user-roles-api` to docker-compose

---

app/upw/index.js
app/upw/upw_config.js
common/assets/sass/application.scss
common/templates/components/feedbackBanner/feedbackBanner.njk
common/templates/layout.njk
common/templates/partials/header.njk

Adds a banner in the footer to link to the feedback form. Adds in a config file for the URL (which can be extended for other items later), and adds the URL to locals for the template to pick up.
Note that the banner does not show if the URL is not in locals, so other services will not show the banner until an appropriate config is added.
This PR also fixes the width of the template footers and changes the service status to 'Beta'.

Arn 865 UPW feedback banner

---

app/upw/templates/cookies.njk

The cookie template had two 'Essential cookies' headings. One was removed.

removed unnecessary second heading in cookies.njk

---

Dockerfile

This hopefully will address some of the Trivy scan alerts the UI has been getting.

Moved docker build to latest version of node LTS

---

app/common/controllers/saveAndContinue.test.js
app/questionGroup/fixtures/expected.json
app/questionGroup/get.controller.test.js
app/rsr/controllers/saveAndContinue.test.js
common/middleware/questionGroups/getHandlers.test.js
common/templates/components/question/template.njk
common/utils/util.js
common/utils/util.test.js
package-lock.json
server.js

This PR updates the templating for 'input' and 'textarea' components to add a 'spellchecker = true' attribute which will enable those fields to be exposed to in-browser spellchecking functionality where available.

Arn 960 add spellchecker attribute

---

app/upw/controllers/common.utils.js
app/upw/controllers/common.utils.test.js
app/upw/controllers/saveAndContinue.js
common/data/hmppsAssessmentApi.js
common/templates/components/mappa-widget/macro.njk
common/templates/components/mappa-widget/template.njk
common/templates/components/risk-flag-widget/template.njk
common/templates/components/rosh-widget/macro.njk
common/templates/components/rosh-widget/template.njk

This PR aims to provide better handling for the RoSH, MAPPA and Flags widgets in the UPW workflow, a few considerations:
- Graceful handling when unable to fetch data, we don't want to prevent use of the rest of the application
- `200` status codes should display and where specific information is unavailable show an appropriate tag
- `404` status codes imply that there is no matching information for the given CRN, we should notify the user in the widget
- Other status codes `400` and above would indicate there is an issue preventing us fetching the data, again we should notify the user in the widget
**RoSH: Everything is fine**
**RoSH: No matching RoSH summary for the given CRN**
**RoSH: Something went wrong**
**MAPPA/Flags: Everything is fine**
**MAPPA/Flags: No matching registrations …

Update ROSH, MAPPA and Flags widgets error handling

---

app/error.njk
app/router.js
helm_deploy/hmpps-risk-assessment-ui/templates/_envs.tpl
helm_deploy/values-development.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server.js

This PR aims to allow testing to provide the Correlation ID when experiencing failures in `dev` this should in **theory** allow us to trace the exact request across our backend services and gain a full picture of what went wrong

Add flag to expose request ID on error pages for debugging

---

app/common/controllers/saveAndContinue.js
app/upw/controllers/gpDetailsSaveAndContinue.js
app/upw/controllers/individualsDetailsSaveAndContinue.js

Updated the `SaveAndContinue` controller to set `rawAnswers` after fetching answers from the backend by default. We were attempting to access these when validating certain pages and they were unset, so hopefully this fixes the issues we were seeing around this

Update SaveAndContinue controller to store rawAnswers after fetching

---

app/upw/templates/individuals-details/individuals-details.njk
app/upw/templates/placement-restrictions/gp-details.njk
server.js

The `Individual declined to give an emergency contact` question was autoselecting on the `Individuals Details` and `GP Details` pages, I've updated the templates so that we're passing a `boolean` to the `checked` attribute for the checkbox group

Fix 'declined' checkbox autoselecting for GP and EC pages

---

app/upw/steps.js

`gp_details_declined` was missing from the `gp-details` step definition, this was causing validation not to run correctly and data not being persisted for this field

Add missing field to GP Details step definition

---

app/upw/fields.js
app/upw/templates/pdf-preview-and-declaration/components/pdf-template/template.njk

Removing the `placement_preference_by_gender_details` field from the `Diversity` section of the UPW PDF template.
This field was removed in `v4` of the UPW PDF and this field looks to be unused in the application.

Remove unused field from UPW PDF template

---

common/assets/sass/_widgets.scss
common/templates/components/rosh-widget/template.njk

This PR updates the Low/No RoSH widgets to include the updated styling and content changes in ARN-1003
Low/No RoSH:

Update styling for Low/No RoSH states

---

app/upw/templates/placement-restrictions/components/disabilities/template.njk

Fixes a bug where disability description from Delius wasn't getting replaced by the UPW one. This bug only affects the disabilities page, the PDF output was unaffected.

Fix disability description override

---

.husky/pre-commit
app/upw/templates/placement-details/availability.njk

This PR updates the template for the 'availability' page to default to unchecked for each option.
The relevant line changes to achieve this are in lines 29-33 of `availabiity.njk` - the other changes are all minor automatic formatting changes. 
Also tweaked the Husky config file to fix a bug when committing using a third party tool like Sourcetree or GitHub desktop.

1052 availability default to no ticks

---

common/templates/partials/offenderDetails.njk

I've added additional context for screen readers for the individuals name, as for the additional identifiers I've added a title to this section as apposed to adding the individuals name to each element to avoid unnecessary repetition

Add title to the identiers list in offender-details

---

app/upw/templates/placement-details/availability.njk
wiremock/responses/assessmentQuestions.json

I've updated the checkbox labels on the UPW Availability page to provide additional context when navigating with a screenreader such as Voiceover. I've made the changes in the Wiremock stubs to test this out and will reflect the changes in the API if we're happy with the implmentation
For example, when navigating the checkboxes with a screenreader the user will be presented with
`Available for work Wednesday evening, ticked, checkbox` when ticked, or `Available for work Wednesday evening, unticked, checkbox` when unticked
This varies from the content described in the ticket, but can't see how we could implement those changes without reverting to Javascript as the checkboxes use a single boolean value 🤔

ARN 934 - UPW availability for work accessibility rework

---

app/upw/templates/diversity-information/cultural-and-religious-adjustments.njk
app/upw/templates/diversity-information/gender-information.njk
app/upw/templates/diversity-information/placement-preferences.njk
app/upw/templates/employment-education-skills/employment-education-skills.njk
app/upw/templates/employment-education-skills/training-employment-opportunities.njk
app/upw/templates/individuals-details/add-emergency-contact.njk
app/upw/templates/individuals-details/edit-contact-details.njk
app/upw/templates/individuals-details/edit-emergency-contact-details.njk
app/upw/templates/individuals-details/edit-personal-details.njk
app/upw/templates/individuals-details/individuals-details.njk
app/upw/templates/placement-details/availability.njk
app/upw/templates/placement-details/equipment.njk
app/upw/templates/placement-details/intensive-working.njk
app/upw/templates/placement-restrictions/caring-commitments.njk
app/upw/templates/placement-restrictions/disabilities-and-mental-health.njk
app/upw/templates/placement-restrictions/edit-gp-details.njk
app/upw/templates/placement-restrictions/gp-details.njk
app/upw/templates/placement-restrictions/health-issues.njk
app/upw/templates/placement-restrictions/travel-information.njk
app/upw/templates/risk-information/managing-risk.njk
app/upw/templates/risk-information/risk-of-harm-in-the-community.njk
app/upw/templates/taskList.njk
common/templates/components/mappa-widget/template.njk
common/templates/components/risk-flag-widget/template.njk
common/templates/components/rosh-widget/template.njk
common/templates/components/widgets/template.njk
common/templates/partials/offenderDetails.njk

Changes in this PR;
- The widgets and Individual's Details become `aside` elements with `aria-label`s, Voiceover will read these out as `<label> complimentary`
- The main form content has been moved to a `section` element, Voiceover will read this out as `Form content region`
- Use of `sections` and `aside` elements allows the user to quickly navigate between these regions using Voiceover
- Added a missing caption to the RoSH risk levels table
- Adjusted the heading elements used in the widgets section
- Added an `aria-label` to the Delius risk flags list, this provides additional context before the list is read out

Update page structure to improve accessibility

---

common/assets/javascripts/app-insights.js

Changes to the way custom properties are set up have changed in later version of the SDK but are not well documented - https://stackoverflow.com/questions/58238507/how-can-i-call-addtelemetryinitializer-when-using-the-latest-javascript-snippet gave insight to what needed changing.

ARN-879 Update AppInsights initialisation to correctly send role name

---

app/error.njk
app/upw/templates/placement-details/availability.njk
common/assets/sass/_upw-pages.scss
common/assets/sass/application.scss
common/templates/components/read-only/template.njk
common/templates/layout.njk
common/templates/partials/header.njk

**Desktop -> Mobile reflow testing**
Due to us using a wide page container I've combined the `mobile` and `tablet`  breakpoints so that we can adjust for a non-desktop experience. It's likely we will want the reflow to happen when we're not at `desktop` resolutions.
The risk widgets on the right will move underneath the main contain when we go below the `desktop` breakpoint. I've put a few styling changes to try and avoid horizontal scrolling when we hit `mobile` resolutions.
Also updated the reflow behaviour for read-only data as part of this PR

Initial fix for reflow issues on UPW availability page

---

common/data/hmppsAssessmentApi.js

This appears to be leftover from the RSR workflow and has no usages

Remove draft predictor method from the assessments client

---

app/common/controllers/saveAndContinue.js
app/common/controllers/saveAndContinue.test.js
app/common/controllers/saveAndContinue.utils.js
app/common/controllers/saveAndContinue.utils.test.js
app/upw/controllers/saveAndContinue.js

This PR intends to limit the local answer cache to just the current page, this will ensure the up to date answers displayed to the user are reflective of what is persisted in the backend.
This does however "break" our local testing for this as we're not relying on the session model for answers and we don't currently persist anything in the backend with Wiremock. I'll look at fixing this in a follow up PR

ARN-1114 - Refactor controllers to limit answers local answers to current page

---

app/upw/controllers/api.js

Using a generic filename here as we would otherwise be required to hit several API endpoints. Given the context in which the file is displayed in Delius, this shouldn't be an issue

Update UPW endpoint to set Content Disposition header in response

---

app/common/controllers/saveAndContinue.utils.js
common/templates/components/question/template.njk

Not sure how long this has been here, but looks like the wrong thing was being passed for validation errors on conditional questions
We would display the summary up top, but the inline error was missing

Fix error messages not showing for conditionals

---

app/upw/templates/confirmation.njk

Removing the PDF download button, this no longer has an endpoint in UPW and can be downloaded in Delius

Remove PDF download button

---

.circleci/config.yml
helm_deploy/hmpps-risk-assessment-ui/Chart.yaml
helm_deploy/hmpps-risk-assessment-ui/values.yaml

This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `12 => 4 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have …

Migrating project to use groups in allowlist
